.github/workflows/linter.yml
README.md

- close #3 
- linter.yml の追加
- README.md にステータスバッジを追加

CI ステータスの追加

---

.git_hooks/commit-msg
README.md

- close #11 
- `.git_hooks/commit-msg` の追加
- README.md に実行権限の付与の旨を追記（わすれてました）

フック用ディレクトリと commit-msg を作成

---

.git_hooks/pre-commit

- close #4 
- `.git_hooks/pre-commit` の追加

コミットごとに linter を走らせる

---

.github/workflows/linter.yml

- close #13 
- `.github/workflows/linter.yml` の修正

チェックアウトの更新

---

.git_hooks/pre-commit
.git_hooks/pre-push

- close #5 
- `.git_hooks/pre-commit` の追加
- `.git_hooks/pre-push` の追加

main ブランチへの commit, push の制限

---

cssConvention.md

close #28 
spをmgに変更
120に対応
方向を追加

spをmgに変更など

---

cssConvention.md
src/common.css

汎用modifierを作成

---

src/pages/TutorialPage/Page1.css
src/pages/TutorialPage/Page1.stories.tsx
src/pages/TutorialPage/Page1.tsx

tutorialの一ページ目を作成

---

src/components/UserIcon/UserIcon.css
src/components/UserIcon/UserIcon.stories.tsx
src/components/UserIcon/UserIcon.tsx

close #42 
UserIconを作成
サイズは
xxs: チャット用
xs: ヘッダーのところのアイコン用
sm: ユーザのリスト用
md: 好き度設定のポップアップ用
lg: ログイン時などの時用

UserIconを作成

---

src/components/WithBackground/BackgroundImage.svg
src/components/WithBackground/WithBackground.stories.tsx
src/components/WithBackground/WithBackground.tsx
src/components/WithBackground/withBackground.css

close #44 
WithBackgroundを作成
WithBackgroundは、背景に
こいつをくっつけます。
ただし、くっつけるだけでその中での配置などはくっつける側でやってください。

WithBackgroundを作成

---

src/components/WithBackground/withBackground.css

WithBackgroundを修正

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

- close #51 
それぞれ assignees を空にした
- feature_request.md
- bug_report.md

assignees を空に変更

---

src/pages/WelcomePage/WelcomePage.tsx
src/pages/WelcomePage/welcomePage.css

Welcomeページを作成

---

.github/workflows/auto-update.yml

- close #59 
- auto-update.yml の追加
- secrets に AUTO_UPDATE_TOKEN の追加

auto update の導入

---

src/pages/CelebrationPage/CelebrationPage.css
src/pages/CelebrationPage/CelebrationPage.stories.tsx
src/pages/CelebrationPage/CelebrationPage.tsx

- close #62 
- CelebrationPage.tsx の更新
- CelebrationPage.css の追加
- CelebrationPage.stories.tsx の修正

CelebrationPage の追加

---

.github/ISSUE_TEMPLATE/refactoring_request.md

- close #70 
- refactoring_request の追加
- これがマージされたなら、`refactoring` ラベルの追加（ラベルの色は未定）

refactoring_request.md の追加

---

.githooks/pre-push

- close #84 
- pre-push で標準入力が渡されなかったときのエラー処理を実装した

pre-push を修正

---

src/App.tsx
src/pages/PowerWordPage/PowerWordPage.tsx
src/pages/PowerWordPage/powerWordPage.css

PowerWordPageを作成

---

src/components/Icon/svgIcons/AddIcon.svg

- close #91 
- .svg ファイルの width と height を 18.67px にした

AddIcon のサイズ修正

---

.stylelintrc.json
package.json
src/App.css
src/components/AddButton/addButton.css
src/components/Button/button.css
src/components/Header/header.css
src/components/HeartRating/useHeartRating.css
src/components/Input/useMessageInput.css
src/components/Input/useSearchInput.css
src/components/UserIcon/UserIcon.css
src/components/WithBackground/withBackground.css
src/hooks/useTab/tab.css
src/pages/CelebrationPage/CelebrationPage.css
src/pages/HakyokuPage/HakyokuPage.css
src/pages/HomePage/homePage.css
src/pages/PowerWordPage/powerWordPage.css
src/pages/SearchPage/userCard.css
src/pages/TutorialPage/Page1.css
src/pages/TutorialPage/Page2.css
src/pages/WelcomePage/welcomePage.css
src/stories/button.css

- close #101 
- npm-scripts の更新
- *.css ファイルを修正

stylelint をかけて修正しよう！

---

src/components/HeartRating/useHeartRating.stories.tsx
src/components/HeartRating/useHeartRating.tsx

- close #104 
- `clearCount()` の追加
- `selectedHeartsCount` -> `selectedCount`

useHeartRatingの修正

---

.eslintrc.json

close #99 
eslintのルール、no-consoleをワーニングに変更

consoleをエラーからワーニングに

---

src/components/Message/Message.stories.tsx
src/components/Message/Message.tsx
src/components/Message/message.css

Messageコンポーネントを作成

---

src/pages/LostPartnerPage/LostPartnerPage.tsx
src/pages/LostPartnerPage/lostPartnerPage.css

close #115 
HakyokuとLostPartnerが逆になってたので修正
Hakyokuについては別途実装し直す。

HakyokuとLostPartnerが逆になってたので修正

---

src/components/RadioButton/RadioButton.stories.tsx
src/components/RadioButton/RadioButton.tsx
src/components/RadioButton/radioButton.css

RadioButtonを作成

---

.eslintrc.json
src/hooks/useLovePoint/useGetLovePoint.tsx
src/hooks/useLovePoint/useLovePoint.stories.tsx
src/hooks/useLovePoint/useLovePoint.tsx
src/pages/TalkRoomPage/TalkRoomPage.tsx

- close #112 
- close #110 
好き度の POST, GET ができるようになった
- useLovePoint(id)
- id に対しての現在の好き度とonClick用の関数を返す関数を返す(日本語がすごい)

useLovePoint の作成

---

src/pages/SearchPage/UserCard.stories.tsx
src/pages/SearchPage/UserCard.tsx
src/pages/SearchPage/userCard.css

- close #133 
- UserCardのCSSを変更した
- storybookを追加
- 長すぎる名前はトリミング(目算で limit を決めている)

UserCardを整えた

---

src/pages/SearchPage/AllTabContent.tsx
src/pages/SearchPage/SearchPage.tsx
src/pages/SearchPage/searchPage.css

- close #135 
- searchPage のアイコン、input を整えた
- フォントを整えた

SearchPageのCSSを整えた

---

src/pages/HomePage/HomePage.tsx

close #140 
コンフリクト解消時のやらかしをなかったことに

コンフリクト解消時のやらかしをなかったことに

---

src/hooks/useDialog/DialogButton.tsx
src/hooks/useDialog/useDialog.css
src/hooks/useDialog/useDialog.tsx
src/hooks/useHakyokuForm/useHakyokuForm.tsx
src/pages/HakyokuProcessPage/HakyokuProcessPage.tsx

- close #137 
- useDialog を作ってHakyokuPageで使った
- まだuseDialogからPowerWordへの繋ぎこみはしていない

破局ダイアログを作って破局ページにくっつけた

---

src/App.tsx
src/lib/fetchWithAuth.ts
src/pages/HomePage/HomePage.tsx
src/pages/SearchPage/FolloweeTabContent.tsx
src/pages/SearchPage/FollowerTabContent.tsx
src/pages/SearchPage/SearchPage.tsx

close #144 
use base url and fetch with auth

use base url and fetch with auth

---

src/pages/SearchPage/AllTabContent.tsx
src/pages/SearchPage/FolloweeTabContent.tsx
src/pages/SearchPage/FollowerTabContent.tsx
src/pages/SearchPage/SearchPage.tsx

- close #132 
以下の UserList を PopupUserList に変更
- FolloweeContent
- FollowerContent
- AllTabContent

SearchPage から　Add できるようにした

---

src/pages/HomePage/HomePage.tsx

fetchの末尾/を修正

---

src/App.tsx
src/components/HeartValue/HeartValue.tsx
src/components/HeartValue/heartValue.css
src/components/LeveledPopupUserList/LeveledPopupUserList.tsx
src/env.ts
src/hooks/UseTwitterLogin.tsx
src/hooks/useGetUserInfo.ts
src/hooks/useLovePoint/useGetLovePoint.tsx
src/hooks/useLovePoint/useInitializedHeartRating.tsx
src/hooks/useLovePoint/useLovePoint.tsx
src/pages/HakyokuProcessPage/HakyokuProcessPage.tsx
src/pages/HomePage/HomePage.tsx
src/pages/HomePage/homePage.css
src/pages/SearchPage/FolloweeTabContent.tsx
src/pages/SearchPage/FollowerTabContent.tsx
src/pages/SearchPage/SearchPage.tsx

baseURLmainとbaseURLlocalをbaseURLにまとめた&HomePageの見た目を整えた

---

src/hooks/useFetchWithAuth.ts
src/hooks/useLovePoint/useLovePoint.tsx
src/lib/fetchWithAuth.ts

close #162 
useFetchWithAuthなどのリファクタリング

useFetchWithAuthなどのリファクタリング

---

src/hooks/useFetchWithAuth.ts
src/pages/CelebrationPage/CelebrationPage.tsx

- close #155 
- close #170 
- `/me/lover/` からURLをとってきて遷移させるようにした
- useFetchWithAuth のバグを直した(詳細→ #170)

celebration ページからトークルームへの遷移

---

src/hooks/useDialog/useDialog.tsx

- close #168 
- baseURL を使用
- fetchWithAuth を使用

useDialog の修正

---

src/pages/LostPartnerPage/LostPartnerPage.tsx

- close #172
- `<Link>` をつけただけ

lost-partner/ から hakyoku/ へ遷移可能にした

---

src/hooks/useFetchWithAuth.ts
src/pages/CelebrationPage/CelebrationPage.tsx

- close #173 
- close #176 
- `/me/lover`から404が返ってきたらlost-partnerへ遷移させた
- `useFetchWithAuth` から statusCode: number を返却するようにした

celebrationからlost-partnerへの遷移

---

src/lib/redirect.ts
src/pages/CelebrationPage/CelebrationPage.tsx
src/pages/HomePage/HomePage.tsx

- close #174 
- redirect を lib の中にした
- `/me/lover` から200が返ってきたら /home から /celebration へリダイレクト

成立してたら/homeから/celebrationへの遷移

---

src/hooks/useDialog/useDialog.tsx
src/lib/redirect.ts

- close #179 
- dialog button の onClick に redirect 操作を追加

破局ダイアログから/power-wordへ飛ぶ

---

src/env.ts

- close #184 
うおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおお

いえいえいえいえいえいえいえい

---

src/env.ts
src/pages/PowerWordPage/PowerWordPage.tsx
src/pages/PowerWordPage/powerWordPage.css

- close #180 
- TopContent と ButtomContent にわけた
- active な ButtomContent に Link を追加した

power word ページを整えた

---

src/pages/CelebrationPage/CelebrationPage.tsx
src/pages/LostPartnerPage/LostPartnerPage.tsx

- close #188 
以下の dummy 情報を消して、ユーザー情報をとってくるようにした
- celebration/
- lost-partner/

ユーザーの情報を使用する

---

src/components/Popup/Popup.css
src/components/Popup/Popup.tsx

- close #193 
aタグを使ってたときよりきれいになりました

ポップアップのscreeNameの表示を直した

---

src/pages/PowerWordPage/powerWordPage.css

格言ページのフォントを修正
